### ISSUE TITLE
[vituum + twig] project build directory

### ISSUE THREAD

**Issue by alexsoin** [vituum/vituum#11]
When building the project, the files are collected in the `public` folder, while the `build.outDir` parameter is ignored. 

_vite.config.js:_

```js
import { defineConfig } from 'vituum';
import twig from '@vituum/twig';

export default defineConfig({
  integrations: [twig()],
  templates: {
    format: 'twig',
  },
  build: {
    outDir: '../dist',
  },
});

```

The `build.rollupOptions.output` option also doesn't work.

_vite.config.js:_

```js
// ...
export default defineConfig({
  // ...
  build: {
    // ...
    rollupOptions: {
      output: {
        entryFileNames: `assets/js/[name].js`,
        chunkFileNames: `assets/js/[name].js`,
        assetFileNames: `assets/[name].[ext]`
      }
    }
  }
});

```

The test was carried out both on a local Linux machine and in a [stackblitz](https://stackblitz.com/github/vituum/vituum/tree/main/examples/twig) environment.

**Comment by lubomirblazekcz** [comment]
You should use `output` option https://vituum.dev/config/main-options.html#output

And Vite options should go into `vite` option. But I agree this might be confusing and I might consider change this in the future that vituum options would go under `vituum` and `vite` options would go directly as config.

**Comment by lubomirblazekcz** [comment]
By default public dir is same as output dir in Vituum, as for the build options, you should add these in to `vite` option. Same goes to `publicDir` option.

See https://vituum.dev/config/

**Comment by alexsoin** [comment]
I probably misunderstood the purpose of vituum... 

I wanted to use it as a tool for layout of sites, with subsequent integration of layout into the CMS, but as I see it, this will not work without rewriting the logic of this tool. It is also not clear how the javascript code is split into chunks, I have two library imports, and everything is placed in one chunk with the name of the last import, and when splitting into chunks is disabled, the assembly breaks. 

Thank you for your work!

**Comment by mrleblanc101** [comment]
Yeah I have a similar goal. I want to move away from Gulp.
Vituum seemed like a good choice since it support Twig template which we use.
Currently, we use Gulp to generate a static version of a website using Twig template, before it's integrated in the chosen CMS templating language (Wordpress, Typo3, Drupal, etc...).
I'm getting close to what I want to do, but I'm facing one last issue. When using `preserveModules: true`, Vituum seems to generate `.js` file for my css and twig template and I don't know why ! Here is my config:

```
export default defineConfig({
    build: {
        manifest: true,
        modulePreload: false,
        rollupOptions: {
            input: [
                './src/templates/emails/*.{json,latte,twig,liquid,njk,hbs,pug,html}',
                './src/templates/pages/**/*.{json,latte,twig,liquid,njk,hbs,pug,html}',
                '!./src/templates/pages/**/*.{latte,twig,liquid,njk,hbs,pug,html}.json'
            ],
            preserveEntrySignatures: "exports-only",
            output: {
                dir: 'build',
                preserveModules: true,
                entryFileNames: `[name].js`,
                chunkFileNames: `[name].js`,
                assetFileNames: `[name].[ext]`
            },
        }
    },
    plugins: [
        vituum({
            pages: {
                normalizeBasePath: true,
                dir: './src/templates/pages',
            },
            imports: {
                filenamePattern: {
                    '+.css': [],
                    '+.scss': 'src/styles'
                }
            },
        }),
        twig({
            root: './src/templates',
            dir: './src/templates/pages',
            base: './src/templates',
            functions: customFunctions,
        }),
    ]
});
```
And here are the 2 files that I don't understand:
<img width="368" alt="Screenshot 2024-01-02 at 10 38 50 PM" src="https://github.com/vituum/vituum/assets/17392251/db71501e-d645-4529-ae2b-00ba9700bfd7">

**Comment by mrleblanc101** [comment]
I was able to fix the `app.scss.js`, weird issue.
My `app.scss` was empty while testing. 
When adding css in it, it render `app.css` correctly.
Now, I only need to find why I get a `templates/pages/index.twig.html2.js`
