### ISSUE TITLE
webstorm: error parsing config vite.config.js

### ISSUE THREAD

**Issue by alexsoin** [vituum/vituum#13]
IDE `WebStorm` constantly displays an error when it cannot parse the config file, and because of this it cannot parse the paths of imported files through aliases. Without the use of `vituum`, there is no such error.

Error:

```
Can't analyze vite.config.js: coding assistance will ignore module resolution rules in this file.
 
Possible reasons: this file is not a valid configuration file or its format is not currently supported by the IDE.
```

![изображение](https://user-images.githubusercontent.com/3787132/224084493-4b049695-151a-4e66-94d2-7789eaa4e2f5.png)

can this be fixed somehow?

**Comment by lubomirblazekcz** [comment]
Can you send me your config? I'm using WebStorm too and never had such a issue.

**Comment by alexsoin** [comment]
https://github.com/alexsoin/pepelac/blob/vite/vite.config.ts

**Comment by alexsoin** [comment]
Does not see the path to [this](https://github.com/alexsoin/pepelac/blob/vite/src/scripts/index.js#L1) import, although the assembly is correct

**Comment by lubomirblazekcz** [comment]
Hmm, I tried myself and I don't see any issue, might be a problem with your WebStorm configuration

**Comment by alexsoin** [comment]
and ctrl+click on import scss works?

https://user-images.githubusercontent.com/3787132/224304430-5f94bc5c-4819-477c-a8d0-07e0cd27016e.mp4
