### ISSUE TITLE
Integrate hbs templating into existing one pager

### ISSUE THREAD

**Issue by nikolailehbrink** [vituum/vituum#18]
Hello, I'm seeking some guidance here rather than reporting a bug or issue. I'm currently working on a really simple one-page website with multiple sections. For one of those sections, I'm keen on incorporating a component or a partial. This is to avoid redundancy and save me the effort of repeatedly coding the same HTML block six times, but with varying text and images.

I came across your repository and was particularly attracted by the concept of data separation that it employs, where the content is laid out separately. I'm curious about how I could adapt this approach to my project. Specifically, I would like to know how I can incorporate these partials into a single index.html or .hbs file. Can you guide me on how to go about this?

**Comment by lubomirblazekcz** [comment]
You can create reusable layout in `hbs` like this https://www.emmanuelgautier.com/blog/snippets/handlebarsjs-layout and in there you can include partials.
