### ISSUE TITLE
Errors when upgrading a project to version 1

### ISSUE THREAD

**Issue by alexsoin** [vituum/vituum#19]
I'm trying to update the project to `vituum` v1, for this a [vituum-v1](https://github.com/alexsoin/pepelac/tree/vituum-v1) branch was created. I ran into some issues with the transfer.

Changing the `pages.dir` parameter to `./src/views` works correctly with `npm run dev`, but `npm run build` ignores the contents of `./src/views`, building html only works if you remove the parameter `pages.dir` and move the contents of `./src/views` back to `./src/pages`.

```js
{
  pages: {
    dir: "./src/views"
  }
}
```

Running `npm run dev` creates `+.js` and `+.css` in the subfolders `./src/scripts` and `./src/styles`.

Running `npm run build` creates `404.twig.js` and `index2.js` in `./dist/assets/js`, although only one is imported into `404.twig` and `index.twig` js file `./src/scripts/index.js`

Tried importing only `pages` separately (to disable the vituum imports plugin) as shown in the documentation:

```js
import pages from 'vituum/plugins/pages.js'
```

In this scenario, `npm run dev` displays pages in the browser correctly, but if you run `npm run build`, the build will stop with an error:

```
Could not resolve entry module "index.html".
```

Also, when importing `pages` like this, vscode swears that it cannot find the module at the given path. Tried changing the import to the following path:

```js
import pages from "vituum/src/plugins/pages.js";
```

But then another error appears on startup:

```
✘ [ERROR] Missing "./src/plugins/pages" specifier in "vituum" package [plugin externalize-deps]
```

Is it possible to disable the script and style collector, or do I need to go some other way to do this?

**Comment by lubomirblazekcz** [comment]
When you change pages directory to something else, you need to also change `build.rollupOptions.input` - https://vituum.dev/config/main-options.html#input (some goes if you use only pages plugin)

You can turn off imports by setting following in vituum config

```javascript
imports: {
    paths: []
}
```

`vituum/plugins/pages.js` should be exported, but I can see the export is not working correctly, will look into that

**Comment by alexsoin** [comment]
Many thanks for your help! 

[Added](https://github.com/alexsoin/pepelac/commit/444988a5c6a4d2131bab1f77ce23a6452095b4e0) `vituum` and `rollup` options, this helped to solve the problem of `+.js` and `+.css` appearing, `html` is now also assembled correctly, but is now created when building `dist/assets/js/404.twig.js` and `dist/assets/css/404.twig.css `, although `dist/assets/js/index.js` and `dist/assets/css/index.css` would be expected. 

Can you suggest how to fix this?

**Comment by lubomirblazekcz** [comment]
You also need to include css and js into `rollupOptions.input`, otherwise rollup takes the name from the html file. So the paths should look like this

[
    './src/views/**/*.{json,twig,html}',
    '!./src/views/**/*.twig.json',
    './src/styles/*.{css,pcss,scss,sass,less,styl,stylus}',
    './src/scripts/*.{js,ts,mjs}'
]

**Comment by alexsoin** [comment]
something went wrong again)))

![изображение](https://github.com/vituum/vituum/assets/3787132/018143f4-8076-4c16-b176-a088c5685c0a)

**Comment by lubomirblazekcz** [comment]
Try adding `modulePreload: false` to `build`, that should remove that extra `404.twig.js`. But I'm not sure why the js entry is renamed to `index2.js`. Happens only when you have `build.rollupOptions.output` and css and js has same name, that is some vite / rollup thing.

**Comment by alexsoin** [comment]
yes, the `modulePreload` option helped get rid of `404.twig.js`, but the output is still `index2.js`

```
dist/assets/css/index.css
dist/assets/js/index2.js
```

interestingly, there was no such problem with `vituum` version `0.x`.

I decided to experiment if I rename `index.js` in `main.js`, then there will be no two at the end of the file name. very strange...

```
dist/assets/css/index.css 
dist/assets/js/main.js
```

maybe it has something to do with `index.twig`? it feels like when building it considers that the name `index.js` is already taken and adds 2 at the end.

**Comment by alexsoin** [comment]
no, it's not related to `index.twig`. now I tried to change the name `index.twig` to `home.twig`, also created `index2.js`
