### ISSUE TITLE
Pages directory setting not working

### ISSUE THREAD

**Issue by superflausch** [vituum/vituum#21]
Maybe we are making an error in our configuration but we are not able to set another directory as our source pages directory. Setting anything else than the default `./src/pages` results in that none of the pages get rendered/created.

I created a basic example at https://stackblitz.com/edit/github-hyh7sd?file=vite.config.js and here is the vite.config.js, which doesn't work:

```
export default {
  plugins: [
    vituum({
      pages: {
        dir: './src/views',
      },
    }),
    twig({
      root: './src',
    }),
  ],
};
```

This is with the new 1.0 release.

PS. Thanks for the work and the 1.0 release.

**Comment by lubomirblazekcz** [comment]
@superflausch you need to change `build.rollupOptions.input` in vite.config when you're changing  pages dir. See https://vituum.dev/config/main-options.html#input or https://vituum.dev/guide/migrating-1-0.html for more info. 

 I can see it's creating some confusion, so I might change this to work automatically in the future 👍
