### ISSUE TITLE
Change default folder

### ISSUE THREAD

**Issue by alkorlos** [vituum/vituum#24]
Hello!

In default vituum routes from `src/pages`. To change it need to use `build.rollupOptions.input`. 
For example if want change folder and add multi-page support need code:
```js
rollupOptions: {
	input: ['./src/templates/pages/*.html']
}
```
But there are several problems with this configuration.

If use this config `npm run build` put files to `dist\templates\pages`, need `dist`
Try use `build.rollupOptions.output`, but it doesn't work for html, full config:
```js
import vituum from 'vituum'

export default {
	build: {
		emptyOutDir: true,
		rollupOptions: {
			input: ['./src/templates/pages/*.html'],
			output: {
				assetFileNames: ({name}) => {
					if (/\.html$/.test(name ?? '')) {
						return '[name]-[extname]';
					}

					if (/\.css$/.test(name ?? '')) {
						return 'css/[name]-[hash][extname]';
					}

					return 'assets/[name]-[hash][extname]';
				},
			},
		},
	},
	plugins: [vituum()]
}
```
After `build` css files in `dist\css` folder, html still in `dist\templates\pages`.

In issue [How to change the path of pug pages when building a project? #5](https://github.com/vituum/vituum/issues/5) written "you should use `vituum build`", but it gives me a error "vituum: command not found"

With `npm run dev` also a problem.
Page http://localhost:5173/ is empty "localhost page not found". index.html have a different link?
Page http://localhost:5173/templates/pages is empty to as well as several other options that I tried.

For determines where pages routing need to use `root`?
```js
plugins: [vituum({
    root: './src/templates/pages'
})]
```
This does not help.

**Comment by lubomirblazekcz** [comment]
When you change pages dir, you need to also change it in the config here https://vituum.dev/plugins/pages.html#dir otherwise it will not work

**Comment by alkorlos** [comment]
Please tell how exactly need to change `dir` in this case?
With this code
```js
plugins: [vituum({
  dir: './src/templates/pages'
})]
```
Same result for `npm run build` and `npm run dev`

**Comment by lubomirblazekcz** [comment]
It's actually

```js
plugins: [vituum({
  pages: {
    dir: './src/templates/pages'
 }
})]
```

**Comment by alkorlos** [comment]
Plagin [imports](https://vituum.dev/plugins/imports.html) give me some bugs, I dont need this plugin, but if
replace
```js
plugins: [vituum({
  pages: {
	  dir: './src/templates/pages'
  }
})],
 ```
 to
 ```js
plugins: [pages({
  dir: './src/templates/pages'
})]
 ```
 
`npm run build` give error
"Could not resolve entry module "./src/templates/pages/*.html".
..."

`npm run dev` give error
"(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling."

The documentation says that plugins can be [used separately](https://vituum.dev/plugins/pages.html#using-separately), is that right?

**Comment by lubomirblazekcz** [comment]
That's correct, but vite and pages plugin it self doesn't support globs inside `rollupOptions.input`, that's something vituum itself (https://github.com/vituum/vituum/blob/main/src/index.js#L26) does automatically via [fast-glob](https://github.com/mrmlnc/fast-glob). You can do that like this

```js
import fg from 'fast-glob'
import { resolve } from 'path'


rollupOptions: {
	input: fg.sync(['./src/templates/pages/*.html']).map(entry => resolve(process.cwd(), entry))
}
```

path is imported from

**Comment by alkorlos** [comment]
An important point if someone will read this

If redefine vite root, example
```js
root: 'src',
```
this will not affect in

```js
input: fg.sync(['./src/templates/pages/*.html']).map(entry => resolve(process.cwd(), entry))
```
need full path with `src`. @lubomirblazekcz correct?

Now this better way to off Imports plugin?

**Comment by lubomirblazekcz** [comment]
I might add `imports: false` as a config options in future release to make it easier
