### ISSUE TITLE
(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.

### ISSUE THREAD

**Issue by igitur** [vituum/vituum#25]
Hi,

New to vite and vituum, so excuse me if this is stilly.

I have just degit'ed vituum and I'm looking at the provided examples.

> degit vituum/vituum/examples

All of the templating examples yield the same warning when I fire them up:
`(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.`

e.g. 
```
cd twig
npm install
npm run dev
```

```
> @example/twig@0.0.1 dev
> vite dev

(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.

  VITE v4.4.9  ready in 1931 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

Why am I getting this warning without having changed anything in the example code?

**Comment by lubomirblazekcz** [comment]
Add following code to your `vite.config.js` to hide the message, maybe will add it by default to vituum. Thanks, for report and don't worry it's not really a problem.

```
optimizeDeps: {
    entries: [],
}
```

**Comment by VuongLinhDinh** [comment]
thank you so much!!!
