### ISSUE TITLE
normalizeBasePath not working on windows

### ISSUE THREAD

**Issue by MartinKostadinov** [vituum/vituum#27]
Hi , i have tried to set normalizeBasePath  in my project on windows. But the path never changes. On mac everything works normal.
 From what i have found the problem is with
` bundle[path].source = bundle[path].source.replaceAll(relative(file, root).replace('../', ''), '.') ` .
 I think `relative`  needs to be normalized  because windows  uses '\\'  not '/' . Ppossible fix could be `bundle[path].source = bundle[path].source.replaceAll(normalizePath(relative(file, root)).replace('../', ''), '.')`

**Comment by DanYellow** [comment]
I've experimented the same issue and found the same solution more or less. Do we need to create an PR for this?

**Comment by ExTeeP** [comment]
I've also encountered the same problem

**Comment by lubomirblazekcz** [comment]
Thanks for the report, I'll fix this in the upcoming version

**Comment by lubomirblazekcz** [comment]
fixed in 1.0.1
