### ISSUE TITLE
Get error ERR_UNSUPPORTED_ESM_URL_SCHEME with command build

### ISSUE THREAD

**Issue by Solunsky** [vituum/vituum#4]
Hello!
Windows: 11
Node: 16.20
Npm: 8.19
In console i see error:
`Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

**Comment by Solunsky** [comment]
I update Node to 18 and work, but posthtml not render in build

**Comment by lubomirblazekcz** [comment]
can you post a repro example? perhaps on stackblitz.com ?

**Comment by lubomirblazekcz** [comment]
can you then send repro on github?

**Comment by Dimox** [comment]
1. Copy [this example](https://github.com/vituum/vituum/tree/main/examples/posthtml) to a new project.
2. Run `npm i`.
3. Run `npm run build`.
4. As result 'public' folder does not contain any html files.

https://user-images.githubusercontent.com/2348058/207274181-85f131f5-c452-4f96-bcb5-12a2ae344b56.mp4

**Comment by lubomirblazekcz** [comment]
@Dimox ok thanks! Might be some problem on Windows, I will take a look at this later

**Comment by lubomirblazekcz** [comment]
@Dimox should be fixed now in https://github.com/vituum/vituum/releases/tag/0.0.38

**Comment by Dimox** [comment]
@lubomirblazekcz thank you so much! Now it works as expected.
