### ISSUE TITLE
How to change the path of pug pages when building a project?

### ISSUE THREAD

**Issue by TiroZit** [vituum/vituum#5]
Hi!

I have configured vituum. At the moment, when the project is being built (npm run build), the pug pages from `src/views/` are going to `dist/views/` How can I change the path during assembly so that pug pages are assembled in `dist/` (without the views folder, that is, in the dist folder itself)

My repository with my configuration: [vituum-gulp-template](https://github.com/TiroZit/vituum-gulp-template)

**Comment by lubomirblazekcz** [comment]
Hi @TiroZit 

you should use `vituum build` command, with that it should work correctly

**Comment by TiroZit** [comment]
I don't use `vituum build` because it gives this error (![image](https://user-images.githubusercontent.com/78494774/201254713-8f3f5b2b-9fbd-4cac-b59f-87c97dbb0af0.png)). It seems to me that it does not find my config, although I specify `vituum build -c config/vite.build.js`. How can this be fixed?

**Comment by lubomirblazekcz** [comment]
oh I see, this is currently not supported, config has to be in root of the project, `vituum build` command doesn't accept any parameters

**Comment by TiroZit** [comment]
Let's say if I use `vitrum build`, but still it doesn't solve my question

**Comment by lubomirblazekcz** [comment]
`vituum build` copies the files directly to `dist` and not `dist/views` and also supports file endings in views like `.pug` or `.json`

You can try it here https://stackblitz.com/github/vituum/vituum/tree/main/examples/pug?file=package.json just run `npm run build` to see what happens.

<img width="258" alt="obrazek" src="https://user-images.githubusercontent.com/6872956/206843896-b4f96264-104a-4f1b-b1f7-28b5f38475fa.png">
