### ISSUE TITLE
Swig support

### ISSUE THREAD

**Issue by rtritto** [vituum/vituum#52]
Add support for [Swig](http://node-swig.github.io/swig-templates) template engine.

Library: [free-swig](https://www.npmjs.com/package/free-swig)

**Comment by rtritto** [comment]
FYI @lubomirblazekcz

**Comment by lubomirblazekcz** [comment]
Sorry no plan on creating a Swig plugin. You are free create your own, you can follow example of how Twig plugin is done - https://github.com/vituum/vite-plugin-twig

https://vituum.dev/guide/template-engines.html#create-your-own-plugin
