### ISSUE TITLE
Exclude Files (JSON) from being processed by Vituum

### ISSUE THREAD

**Issue by superflausch** [vituum/vituum#7]
We have a couple of (example data) JSON files within our project (/data/categories.json etc.), which are requested and processed from the front-end. Those should not be processed by the template engines and only be served by the server when called from the front-end.

Right now those get processed by vituum and lead to errors like this one:

```
Error: ENOENT: no such file or directory, open '/abcdef/src/views/data/categories.json.html'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at file:///abcdef/node_modules/vituum/plugins/middleware.js:48:142 
```

What's the approach here? Is there a setting to exclude certain files? Should I change the project structure somehow?

Cheers

**Comment by superflausch** [comment]
This happened when using the nunjucks integration. I now switched to the twig integration and this behaviour/error is now gone. Maybe I changed something else too, but I think nothing relevant.

**Comment by superflausch** [comment]
This behaviour/error is now gone. I'm not sure what exactly resolved it. We changed from the nunjucks to the twig integration and did some cleanup of the templates.

I guess you (or I) can close the issue. Sorry.

**Comment by lubomirblazekcz** [comment]
If you have such data, you should generally add it to public directory not in src/views 👍

**Comment by superflausch** [comment]
@lubomirblazekcz Thanks for your reply and sorry to bother you again. This issue emerged again. I'm a little confused why, I'm not sure what changed.

Thing is, those files are not within the `src/views` directory, they are in `public/data`. Here is my vite.config.js file:

`import { defineConfig } from 'vituum'
import twig from '@vituum/twig'

// POSTCSS
import autoprefixer from 'autoprefixer'
import postcssImport from 'postcss-import'
import postcssNested from 'postcss-nested'
import postcssCustomMedia from 'postcss-custom-media'
import postcssImportExtGlob from 'postcss-import-ext-glob'

export default defineConfig({
  integrations: [twig()],
  templates: {
    format: 'twig',
  },
  output: 'dist',
  vite: {
    css: {
      postcss: {
        plugins: [
          autoprefixer,
          postcssImportExtGlob,
          postcssImport,
          postcssNested,
          postcssCustomMedia,
        ],
      },
    },
  },
})
`

Any ideas? Cheers.

**Comment by superflausch** [comment]
The request from the front-end is a simple JS fetch request for `http://localhost:5173/data/brands.json` as an example. This request triggers the error and halts the whole vite script/server.

**Comment by superflausch** [comment]
I did some additional testing. Looks like this gets triggered because the files couldn't be found within my `public` folder (Vite publicDir), so it tries to load them from other locations I guess.

If I change `vite.root` to `./` the files are served again, but this messes up other stuff.

If I add the files directly into my output folder (`dist`) everything works as well.

So It looks to my that Vituum changes something for vite's Public Directory behaviour (https://vitejs.dev/guide/assets.html#the-public-directory) or my understanding of it is wrong.
