### ISSUE TITLE
Server HMR error messages only flashing

### ISSUE THREAD

**Issue by superflausch** [vituum/vituum#8]
After altering our existing Vite project to Vituum the HMR error message overlay only flashes briefly in the browser before disappearing.

Restarting vite will render the error message once, after a browser refresh or a refresh because of a file change the error message will only flash briefly again.

Any ideas what could cause this behaviour?

Cheers

**Comment by lubomirblazekcz** [comment]
could you send a repro? or vite.config.js atleast?

**Comment by superflausch** [comment]
I hope the vite.config.js helps.

```
import { defineConfig } from 'vituum'
import twig from '@vituum/twig'

// POSTCSS
import autoprefixer from 'autoprefixer'
import postcssImport from 'postcss-import'
import postcssNested from 'postcss-nested'
import postcssCustomMedia from 'postcss-custom-media'
import postcssImportExtGlob from 'postcss-import-ext-glob'

export default defineConfig({
  integrations: [twig()],
  templates: {
    format: 'twig',
  },
  output: 'dist',
  vite: {
    css: {
      postcss: {
        plugins: [
          autoprefixer,
          postcssImportExtGlob,
          postcssImport,
          postcssNested,
          postcssCustomMedia,
        ],
      },
    },
  },
})
```

**Comment by lubomirblazekcz** [comment]
Thanks, I've been able to reproduce this in Chrome, works in Firefox though. Should be fixed in plugin now -> https://github.com/vituum/vite-plugin-twig/commit/3c33dd5a248f3764b3c37a6386210e9ab626e46a

Update your deps in project, eg. with `npm update` and should be fixed now.
